/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './../app/routes/__root'
import { Route as NoteImport } from './../app/routes/note'
import { Route as LoginImport } from './../app/routes/login'
import { Route as KnowledgeImport } from './../app/routes/knowledge'
import { Route as KanbanImport } from './../app/routes/kanban'
import { Route as InboxImport } from './../app/routes/inbox'
import { Route as GoalsImport } from './../app/routes/goals'
import { Route as CodStatusImport } from './../app/routes/cod-status'
import { Route as AvatarImport } from './../app/routes/avatar'
import { Route as IndexImport } from './../app/routes/index'
import { Route as OauthConsentImport } from './../app/routes/oauth/consent'
import { Route as KnowledgeSearchImport } from './../app/routes/knowledge.search'
import { Route as KnowledgeGraphImport } from './../app/routes/knowledge.graph'

// Create/Update Routes

const NoteRoute = NoteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgeRoute = KnowledgeImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRoute,
} as any)

const KanbanRoute = KanbanImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRoute,
} as any)

const InboxRoute = InboxImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRoute,
} as any)

const GoalsRoute = GoalsImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRoute,
} as any)

const CodStatusRoute = CodStatusImport.update({
  id: '/cod-status',
  path: '/cod-status',
  getParentRoute: () => rootRoute,
} as any)

const AvatarRoute = AvatarImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OauthConsentRoute = OauthConsentImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgeSearchRoute = KnowledgeSearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => KnowledgeRoute,
} as any)

const KnowledgeGraphRoute = KnowledgeGraphImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => KnowledgeRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarImport
      parentRoute: typeof rootRoute
    }
    '/cod-status': {
      id: '/cod-status'
      path: '/cod-status'
      fullPath: '/cod-status'
      preLoaderRoute: typeof CodStatusImport
      parentRoute: typeof rootRoute
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsImport
      parentRoute: typeof rootRoute
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxImport
      parentRoute: typeof rootRoute
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanImport
      parentRoute: typeof rootRoute
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/note': {
      id: '/note'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof NoteImport
      parentRoute: typeof rootRoute
    }
    '/knowledge/graph': {
      id: '/knowledge/graph'
      path: '/graph'
      fullPath: '/knowledge/graph'
      preLoaderRoute: typeof KnowledgeGraphImport
      parentRoute: typeof KnowledgeImport
    }
    '/knowledge/search': {
      id: '/knowledge/search'
      path: '/search'
      fullPath: '/knowledge/search'
      preLoaderRoute: typeof KnowledgeSearchImport
      parentRoute: typeof KnowledgeImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface KnowledgeRouteChildren {
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  KnowledgeSearchRoute: typeof KnowledgeSearchRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  KnowledgeSearchRoute: KnowledgeSearchRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/cod-status': typeof CodStatusRoute
  '/goals': typeof GoalsRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/note': typeof NoteRoute
  '/knowledge/graph': typeof KnowledgeGraphRoute
  '/knowledge/search': typeof KnowledgeSearchRoute
  '/oauth/consent': typeof OauthConsentRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/cod-status': typeof CodStatusRoute
  '/goals': typeof GoalsRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/note': typeof NoteRoute
  '/knowledge/graph': typeof KnowledgeGraphRoute
  '/knowledge/search': typeof KnowledgeSearchRoute
  '/oauth/consent': typeof OauthConsentRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/cod-status': typeof CodStatusRoute
  '/goals': typeof GoalsRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/note': typeof NoteRoute
  '/knowledge/graph': typeof KnowledgeGraphRoute
  '/knowledge/search': typeof KnowledgeSearchRoute
  '/oauth/consent': typeof OauthConsentRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar'
    | '/cod-status'
    | '/goals'
    | '/inbox'
    | '/kanban'
    | '/knowledge'
    | '/login'
    | '/note'
    | '/knowledge/graph'
    | '/knowledge/search'
    | '/oauth/consent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatar'
    | '/cod-status'
    | '/goals'
    | '/inbox'
    | '/kanban'
    | '/knowledge'
    | '/login'
    | '/note'
    | '/knowledge/graph'
    | '/knowledge/search'
    | '/oauth/consent'
  id:
    | '__root__'
    | '/'
    | '/avatar'
    | '/cod-status'
    | '/goals'
    | '/inbox'
    | '/kanban'
    | '/knowledge'
    | '/login'
    | '/note'
    | '/knowledge/graph'
    | '/knowledge/search'
    | '/oauth/consent'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvatarRoute: typeof AvatarRoute
  CodStatusRoute: typeof CodStatusRoute
  GoalsRoute: typeof GoalsRoute
  InboxRoute: typeof InboxRoute
  KanbanRoute: typeof KanbanRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LoginRoute: typeof LoginRoute
  NoteRoute: typeof NoteRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvatarRoute: AvatarRoute,
  CodStatusRoute: CodStatusRoute,
  GoalsRoute: GoalsRoute,
  InboxRoute: InboxRoute,
  KanbanRoute: KanbanRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LoginRoute: LoginRoute,
  NoteRoute: NoteRoute,
  OauthConsentRoute: OauthConsentRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/avatar",
        "/cod-status",
        "/goals",
        "/inbox",
        "/kanban",
        "/knowledge",
        "/login",
        "/note",
        "/oauth/consent"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/avatar": {
      "filePath": "avatar.tsx"
    },
    "/cod-status": {
      "filePath": "cod-status.tsx"
    },
    "/goals": {
      "filePath": "goals.tsx"
    },
    "/inbox": {
      "filePath": "inbox.tsx"
    },
    "/kanban": {
      "filePath": "kanban.tsx"
    },
    "/knowledge": {
      "filePath": "knowledge.tsx",
      "children": [
        "/knowledge/graph",
        "/knowledge/search"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/note": {
      "filePath": "note.tsx"
    },
    "/knowledge/graph": {
      "filePath": "knowledge.graph.tsx",
      "parent": "/knowledge"
    },
    "/knowledge/search": {
      "filePath": "knowledge.search.tsx",
      "parent": "/knowledge"
    },
    "/oauth/consent": {
      "filePath": "oauth/consent.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
